### ISSUE TITLE
TensorBoard fails on CartPole example

### ISSUE THREAD

**Issue by erlenlok** [matthiasplappert/keras-rl#78]
I appended/modified this snippet:

`log_filepath = "temp/logs"`
`tb = TensorBoard (log_dir=log_filepath, histogram_freq=1)`
`dqn.fit(env, nb_steps=50000, visualize=True, verbose=2, callbacks=[tb])`

to dqn_cartpole.py and got the following error:

`Traceback (most recent call last):
  File "keras_rl_test.py", line 50, in <module>
    dqn.fit(env, nb_steps=50000, visualize=True, verbose=2, callbacks=[tb])
  File "/home/user/anaconda/lib/python2.7/site-packages/rl/core.py", line 41, in fit
    callbacks.set_model(self)
  File "/home/user/anaconda/lib/python2.7/site-packages/keras/callbacks.py", line 51, in set_model
    callback.set_model(model)
  File "/home/user/anaconda/lib/python2.7/site-packages/keras/callbacks.py", line 584, in set_model
    for layer in self.model.layers:
AttributeError: 'DQNAgent' object has no attribute 'layers'
`

**Comment by matthiasplappert** [comment]
The problem is that the agent "acts" as the Keras model, which it really isn't. We could probably fix this by overriding all necessary methods and forwarding them to the underlying model. The problem then is what happens if an agent requires multiple models (like DDPG or NAF). Not sure how to tackle this.

It is probably the best solution right now if you adapt the `TensorFlow` callback to your needs manually. Not a great solution, I know.

**Comment by bstriner** [comment]
Just setting the layers attribute should get most things to work. 

@erlenlok if you add something like `dqn.layers = v_model.layers` or whatever your internal model is, how far does it get?

Cheers

**Comment by matthiasplappert** [comment]
Addressed in https://github.com/matthiasplappert/keras-rl/commit/4c854ea70cbe1a7dfcb2182878c7a5247fd3597b. Keras-RL should now work with `keras.callbacks.TensorBoard` out of the box.

**Comment by MartinThoma** [comment]
I'm not sure if I'm using it the wrong way or if it is not working:

```
from keras.callbacks import TensorBoard
from rl.agents.dqn import DQNAgent

tb = TensorBoard(log_dir='.')
memory = SequentialMemory(limit=1000000, window_length=WINDOW_LENGTH)
agent = DQNAgent(model=model, nb_actions=nb_actions, policy=policy,
                     memory=memory,
                     nb_steps_warmup=50000, gamma=.99,
                     target_model_update=10000,
                     train_interval=4, delta_clip=1.)
agent.compile(Adam(lr=.00025), metrics=['mae'])
agent.fit(env, nb_steps=100000, visualize=False, verbose=2, callbacks=[tb])
```

gives

```
    Training for 100000 steps ...
    Traceback (most recent call last):
      File "dqn_simple.py", line 116, in <module>
        main(args.environment)
      File "dqn_simple.py", line 78, in main
        agent.fit(env, nb_steps=100000, visualize=False, verbose=2, callbacks=[tb])
      File "/usr/local/lib/python3.5/dist-packages/rl/core.py", line 215, in fit
        callbacks.on_episode_end(episode, episode_logs)
      File "/usr/local/lib/python3.5/dist-packages/rl/callbacks.py", line 59, in on_episode_end
        callback.on_epoch_end(episode, logs=logs)
      File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 783, in on_epoch_end
        summary_value.simple_value = value.item()
    AttributeError: 'int' object has no attribute 'item'
    Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f9c52f91940>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 701, in __del__
    TypeError: 'NoneType' object is not callable
```

**Comment by ikamensh** [comment]
I am also affected by this issue. I have fixed it by 

`try:
    summary_value.simple_value = value.item()
except AttributeError:
    summary_value.simple_value = value`

but would make sense to have a solution to root cause.

**Comment by guillem74** [comment]
@ikamensh This still does not work...

Gives me AttributeError: 'int' object has no attribute 'item'
